name: "command demo"

# the workflow to execute on is comments that are newly created
on:
  issue_comment:
    types: [created]

# permissions needed for reacting to IssueOps commands on issues and PRs
permissions:
  pull-requests: write
  issues: write
  checks: read

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      # Checkout your projects repository
      - uses: actions/checkout@v3
      # execute IssueOps command logic, hooray!
      # this will be used to "gate" all future steps below
      - uses: github/command@v1.1.0
        id: command
        with:
          command: ".ping"
          allowed_contexts: "pull_request,issue"
          param_separator: "|"

      # run your custom logic for your project here - example seen below

      - name: commands
        if: ${{ steps.command.outputs.continue == 'true' }}
        run: echo "Commands ${{ toJson(steps.command.outputs) }}"
      
      # conditionally run some logic here
      - name: ping
        if: ${{ steps.command.outputs.continue == 'true' }}
        run: |-
            echo "I am going to ping some cool website now!"
            echo "params: ${{ steps.command.outputs.params }}"

      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: |-
            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.**
            :sparkles: Thank you for your contribution! :sparkles:              
            Params: ${{ steps.command.outputs.params }}
            
        